name: app_and_monitoring

volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
  postgres_data: {}

networks:
  prometheus:
  loki:
  postgres:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipes_project
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipes_project"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      # Conecta a aplicação às redes necessárias
      - prometheus
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:12345@db:5432/recipes_project
      PYTHONUNBUFFERED: 1
    depends_on:
      # Garante que a aplicação inicie após os serviços de monitoramento
      - loki
      - prometheus
      - db
      - tempo

  grafana:
    image: grafana/grafana:12.0.0
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: on-failure
    networks:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:v3.4.1
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=60d'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: on-failure
    networks:
      - prometheus

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped

  loki:
    image: grafana/loki:3.5.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml
      - ./loki/tsdb:/data/tsdb
      - ./loki/retention:/data/retention
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      loki:
        aliases:
          - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    restart: on-failure
    networks:
      - loki

  init-tempo:
    image: &tempoImage grafana/tempo:2.8.0
    user: root
    entrypoint: 
    - "chown"
    - "10001:10001"
    - "/var/tempo"
    volumes:
    - ./tempo-data:/var/tempo

  memcached:
    image: memcached:1.6.38
    container_name: memcached
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4
    ports:
      - "11211:11211"
    networks:
      - prometheus

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200" 
      - "4317:4317"  
      - "4318:4318"
    depends_on:
      - init-tempo
      - memcached
    networks:
      - prometheus

  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.7
    environment:
      - ENDPOINT=tempo:4317
    restart: always
    depends_on:
      - tempo
    networks:
      - prometheus