global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'wsl'
    static_configs:
      - targets:
        - '172.21.0.1:9100'

  - job_name: 'web_metrics'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['web:8000']
        labels:
          # Adicione rótulos que podem ser úteis para filtrar métricas no Grafana
          application: 'web'
          environment: 'development' # Ou 'production', etc.